# Generated by Django 5.2.3 on 2025-06-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(models.OrderBy(models.F('id')), name='id_order_idx'),
        ),
    ]
